### ISSUE TITLE
Flaky test `test_resolve_symbol_commit_id`

### ISSUE THREAD

**Issue by ilyagr** [martinvonz/jj#1024]
In https://github.com/martinvonz/jj/actions/runs/3912455945/jobs/6687119802, a test failed the `linux-msrv` run as follows. Rerunning it fixed the problem.

```
test test_resolve_symbol_commit_id ... FAILED

failures:

---- test_resolve_symbol_commit_id stdout ----
thread 'test_resolve_symbol_commit_id' panicked at 'assertion failed: `Ok([CommitId("0468f7da8de2ce442f512aacf83411d26cd2e0cf")])` does not match `Err(RevsetError::NoSuchRevision(s)) if s == "040"`', lib/tests/test_revset.rs:129:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: test_revset::test_resolve_symbol_commit_id
             at ./tests/test_revset.rs:129:5
   3: test_revset::test_resolve_symbol_commit_id::{{closure}}
             at ./tests/test_revset.rs:47:1
   4: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    test_resolve_symbol_commit_id

test result: FAILED. 58 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.55s

error: test failed, to rerun pass '-p jujutsu-lib --test test_revset'
Error: Process completed with exit code 101.
```

**Comment by yuja** [comment]
Maybe it needs to stabilize change id so it won't start with "040"? Just a guess.

**Comment by martinvonz** [comment]
> Maybe it needs to stabilize change id so it won't start with "040"? Just a guess.

Sounds like a good guess :)
