### ISSUE TITLE
jj started failing on a repo that was working fine

### ISSUE THREAD

**Issue by tp-woven** [martinvonz/jj#258]
## Description

Not sure what happened, but a repo that was working fine yesterday, suddenly jj is failing when trying to check log, status, etc. I tried reindexing (`jj debug reindex`) but it didn't change anything.

This is the error/stack trace:

```
❯ RUST_BACKTRACE=1 jj status
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 102, kind: Uncategorized, message: "Operation not supported on socket" }', lib/src/working_copy.rs:284:42
stack backtrace:
   0: rust_begin_unwind
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/result.rs:1613:5
   3: jujutsu_lib::working_copy::TreeState::write_path_to_store
   4: jujutsu_lib::working_copy::TreeState::write_tree
   5: jujutsu_lib::working_copy::LockedWorkingCopy::write_tree
   6: jujutsu::commands::WorkspaceCommandHelper::maybe_commit_working_copy
   7: jujutsu::commands::cmd_status
   8: jujutsu::commands::dispatch
   9: jj::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

# Or with full backtrace:
❯ RUST_BACKTRACE=full jj status
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 102, kind: Uncategorized, message: "Operation not supported on socket" }', lib/src/working_copy.rs:284:42
stack backtrace:
   0:        0x10647acc1 - std::backtrace_rs::backtrace::libunwind::trace::haa51d71de8c12f2c
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x10647acc1 - std::backtrace_rs::backtrace::trace_unsynchronized::hcd4ce94258793c68
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10647acc1 - std::sys_common::backtrace::_print_fmt::hdd3daf13a4020acc
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x10647acc1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h428cf6d3383daa9c
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x10649bfeb - core::fmt::write::hcf88e896ec23e052
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/fmt/mod.rs:1149:17
   5:        0x106474c5a - std::io::Write::write_fmt::h58c3052bb04c456d
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/io/mod.rs:1697:15
   6:        0x10647c8d5 - std::sys_common::backtrace::_print::h8e57757c05894dea
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x10647c8d5 - std::sys_common::backtrace::print::h105de75e3b91cab9
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x10647c8d5 - std::panicking::default_hook::{{closure}}::h99b76afd6b358916
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:211:50
   9:        0x10647c4bf - std::panicking::default_hook::hd7fbc9eda5da2259
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:228:9
  10:        0x10647cfc0 - std::panicking::rust_panic_with_hook::h48eeb24de18c027c
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:606:17
  11:        0x10647ca5e - std::panicking::begin_panic_handler::{{closure}}::h1cb76dc2cf734090
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:502:13
  12:        0x10647b137 - std::sys_common::backtrace::__rust_end_short_backtrace::h6ba95b68f495d865
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/sys_common/backtrace.rs:139:18
  13:        0x10647c9ca - rust_begin_unwind
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:498:5
  14:        0x1064f465f - core::panicking::panic_fmt::h91749835f0f98da6
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/panicking.rs:107:14
  15:        0x1064f4745 - core::result::unwrap_failed::h27bd9e37a763047a
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/result.rs:1613:5
  16:        0x105ef9c73 - jujutsu_lib::working_copy::TreeState::write_path_to_store::h9589c00e137701f8
  17:        0x105ef8a98 - jujutsu_lib::working_copy::TreeState::write_tree::h4285424f3ff5a199
  18:        0x105efdc93 - jujutsu_lib::working_copy::LockedWorkingCopy::write_tree::hb12f9ead08d440b4
  19:        0x105d42b00 - jujutsu::commands::WorkspaceCommandHelper::maybe_commit_working_copy::h07aa32579fbbafb1
  20:        0x105d53ebd - jujutsu::commands::cmd_status::h0c56b059d4b8a5e1
  21:        0x105d2d024 - jujutsu::commands::dispatch::hf4b5583f4bd3d0c6
  22:        0x105d326af - jj::main::h682a55f4cdaed63e
  23:        0x105d354d6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2aff0c534552faaf
  24:        0x105d354ec - std::rt::lang_start::{{closure}}::hef6879b9874b4439
  25:        0x10647a96f - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h4dd0f8c7b850f348
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/ops/function.rs:259:13
  26:        0x10647a96f - std::panicking::try::do_call::h87be4eed64f35c01
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:406:40
  27:        0x10647a96f - std::panicking::try::hff817004c8a737c1
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:370:19
  28:        0x10647a96f - std::panic::catch_unwind::h6d209170f63e98ac
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panic.rs:133:14
  29:        0x10647a96f - std::rt::lang_start_internal::{{closure}}::h0168cc1e28682b0d
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/rt.rs:128:48
  30:        0x10647a96f - std::panicking::try::do_call::h8d63645390643972
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:406:40
  31:        0x10647a96f - std::panicking::try::h0ced96fd1d070610
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:370:19
  32:        0x10647a96f - std::panic::catch_unwind::h700c7180333c2e66
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panic.rs:133:14
  33:        0x10647a96f - std::rt::lang_start_internal::h240e1720b3cdfa5e
                               at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/rt.rs:128:20
  34:        0x105d32b29 - _main
```

## Specifications

- Platform: macOS 12.3.1
- Version: 0.4.0

**Comment by martinvonz** [comment]
Sorry about that. Was your binary the pre-built from https://github.com/martinvonz/jj/releases? Assuming it was, can you build from source instead, after modifying working_copy.rs:284 to look like as follows?

```
        let file = File::open(disk_path).expect(&format!("failed to open {:?}", disk_path));
```

That will hopefully provide an error message telling us which file is causing the problem. Maybe a permissions issue?

**Comment by tp-woven** [comment]
> Was your binary the pre-built from https://github.com/martinvonz/jj/releases?

I installed jj via `cargo install --git https://github.com/martinvonz/jj.git`, so I don't think so? But I can try to clone the latest version, make the modification, and try to run the local build (something like `cargo run -- -R <path/to/repo>` should work, right?)

**Comment by martinvonz** [comment]
I think [this is the line to modify](https://github.com/martinvonz/jj/blob/78da5596b7202c75c0df956e144b697727ca096e/lib/src/working_copy.rs#L317) (no longer 284 at head).

Yes, you should be able to run that way. You can also do `cargo build --release` to get a faster binary (it's quite significant) and then run that from `target/release/jj`.

**Comment by tp-woven** [comment]
Hmm, so I'm not sure what I did, but I'm not seeing the errors anymore? 😓 

Building from source and running with `cargo run` from head, not even changing the log, succeeded. Then, I tried using the "system" jj from the repo, and that worked too.

**Comment by martinvonz** [comment]
Well, I'm glad it's working again at least. Feel free to leave this open and we can use it for tracking work to improve this error handling.

**Comment by tp-woven** [comment]
This just happened to me again, with a more meaningful error message this time:

```
❯ RUST_BACKTRACE=1 jj st
thread 'main' panicked at 'Working copy lock was dropped without being closed.', lib/src/working_copy.rs:1067:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: <jujutsu_lib::working_copy::LockedWorkingCopy as core::ops::drop::Drop>::drop
   3: core::ptr::drop_in_place<jujutsu_lib::working_copy::LockedWorkingCopy>
   4: jujutsu::commands::WorkspaceCommandHelper::maybe_commit_working_copy
   5: jujutsu::commands::cmd_status
   6: jujutsu::commands::dispatch
   7: jj::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by martinvonz** [comment]
I think I see what could cause that; that error is hiding the real error. As a workaround, you can safely delete https://github.com/martinvonz/jj/blob/ca5a2391abb6f8f5f660f1c35a0cda74f1da9365/lib/src/working_copy.rs#L1064-L1073 and build a new binary.

**Comment by tp-woven** [comment]
Thanks! Now I'm getting a different error:

```
❯ jj l
Internal error: Failed to snapshot the working copy: FileOpenError { path: "/Users/XXXXXX/dev/XXXXXX/XXXXXX/tools/autogazelle/autogazelle.socket", err: Os { code: 102, kind: Uncategorized, message: "Operation not supported on socket" } }
```

(In case you're not familiar with it, autogazelle is a tool to automatically generate Bazel build files for Golang projects, and it uses a socket to communicate with a "server" process.)

I confirmed that `.gitignore`-ing that socket solves the issue, but I wonder if `jj` should be able to handle this gracefully (maybe just ignore sockets?)

**Comment by martinvonz** [comment]
> (In case you're not familiar with it, autogazelle is a tool to automatically generate Bazel build files for Golang projects, and it uses a socket to communicate with a "server" process.)
> 
> I confirmed that `.gitignore`-ing that socket solves the issue, but I wonder if `jj` should be able to handle this gracefully (maybe just ignore sockets?)

Interesting. Yes, it definitely seems like `jj` should ignore sockets. That should be easy to fix, I'll take a look right away.
