### ISSUE TITLE
`test_gc` is very flaky

### ISSUE THREAD

**Issue by thoughtpolice** [martinvonz/jj#3537]
`test_git_backend::test_gc` fails a relatively large amount of the time for me when I run the whole workspace, making `cargo nextest run --workspace` very difficult to use.

Note that I never see this when running solely this test and nothing else; my machine has 12 threads/6 cores, and nextest does well to saturate those cores, so I assume this is another concurrency bug that only happens under load.

```
--- STDOUT:              jj-lib::runner test_git_backend::test_gc ---

running 1 test
git version 2.44.0
test test_git_backend::test_gc ... FAILED

failures:

failures:
    test_git_backend::test_gc

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 313 filtered out; finished in 0.45s


--- STDERR:              jj-lib::runner test_git_backend::test_gc ---
thread 'test_git_backend::test_gc' panicked at lib/tests/test_git_backend.rs:151:5:
assertion `left == right` failed
  left: {CommitId("2b77d9134466c287c377c8b1910ed109a14176e2"), CommitId("6dd9bc207f872d28eb07f0ace0ff88690c113a28")}
 right: {CommitId("2b77d9134466c287c377c8b1910ed109a14176e2"), CommitId("6dd9bc207f872d28eb07f0ace0ff88690c113a28"), CommitId("5081332820ba839700a42b13cca24ca23053d078")}
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:342:17
   3: core::panicking::assert_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:297:5
   4: runner::test_git_backend::test_gc
             at ./tests/test_git_backend.rs:151:5
   5: runner::test_git_backend::test_gc::{{closure}}
             at ./tests/test_git_backend.rs:46:13
   6: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by martinvonz** [comment]
Is it reproducible enough for you that you think you can bisect it? Maybe it started happening after the recent upgrade of `gix`.

**Comment by yuja** [comment]
Appears that it can fail if `git gc` doesn't pack refs for some reasons. I'll send a fix.
