### ISSUE TITLE
crashes if you rename the clone

### ISSUE THREAD

**Issue by krupan** [martinvonz/jj#72]
## Expected Behavior
no crash

## Actual Behavior
jj commands all fail with this error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', lib/src/git_backend.rs:95:87
```

With `RUST_BACKTRACE=1`:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', lib/src/git_backend.rs:95:87
stack backtrace:
   0: rust_begin_unwind
             at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/core/src/result.rs:1749:5
   3: jujutsu_lib::git_backend::GitBackend::load
   4: jujutsu_lib::store::Store::load_store
   5: jujutsu_lib::repo::RepoLoader::init
   6: jujutsu_lib::workspace::Workspace::load
   7: jujutsu::commands::CommandHelper::workspace_helper
   8: jujutsu::commands::cmd_status
   9: jujutsu::commands::dispatch
  10: jj::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
with `RUST_BACKTRACE=full`:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', lib/src/git_backend.rs:95:87
stack backtrace:
   0:     0x55e0d0f2f2bc - std::backtrace_rs::backtrace::libunwind::trace::hede7dd98ee70976c
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55e0d0f2f2bc - std::backtrace_rs::backtrace::trace_unsynchronized::hbe38aeb3ff19fa80
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e0d0f2f2bc - std::sys_common::backtrace::_print_fmt::h8d729be0339480ac
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55e0d0f2f2bc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h44d89a7c637ba906
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55e0d0f58dcc - core::fmt::write::haccb55fe49c41c09
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/core/src/fmt/mod.rs:1190:17
   5:     0x55e0d0f28b08 - std::io::Write::write_fmt::h50fec3265e31260a
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/std/src/io/mod.rs:1657:15
   6:     0x55e0d0f314f7 - std::sys_common::backtrace::_print::h5147f75d54ad7c1f
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55e0d0f314f7 - std::sys_common::backtrace::print::hc83faab68ce2b380
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55e0d0f314f7 - std::panicking::default_hook::{{closure}}::ha61fc22abb98b6b0
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/std/src/panicking.rs:295:22
   9:     0x55e0d0f311af - std::panicking::default_hook::h89b0e33dd598a21f
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/std/src/panicking.rs:314:9
  10:     0x55e0d0f31c4b - std::panicking::rust_panic_with_hook::h7e9579ddfea6f147
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/std/src/panicking.rs:698:17
  11:     0x55e0d0f31937 - std::panicking::begin_panic_handler::{{closure}}::h1e78bb9730f8cca8
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/std/src/panicking.rs:588:13
  12:     0x55e0d0f2f784 - std::sys_common::backtrace::__rust_end_short_backtrace::h3c102b80f36ee941
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55e0d0f31649 - rust_begin_unwind
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/std/src/panicking.rs:584:5
  14:     0x55e0d0989e63 - core::panicking::panic_fmt::hd296f17a12340ce5
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/core/src/panicking.rs:142:14
  15:     0x55e0d0989f53 - core::result::unwrap_failed::hdc2a9475cf94f36c
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/core/src/result.rs:1749:5
  16:     0x55e0d0a6bab3 - jujutsu_lib::git_backend::GitBackend::load::h8e00b520cb2414d6
  17:     0x55e0d0a550a5 - jujutsu_lib::store::Store::load_store::hd78181dba576da40
  18:     0x55e0d0aceb3c - jujutsu_lib::repo::RepoLoader::init::hd62d9b61aa18d3fe
  19:     0x55e0d0a8cb6f - jujutsu_lib::workspace::Workspace::load::h48d2ebfe0b508579
  20:     0x55e0d0995aea - jujutsu::commands::CommandHelper::workspace_helper::h0ee8ceb4aacc4b23
  21:     0x55e0d09b6dba - jujutsu::commands::cmd_status::hc1dcdccdc68451e6
  22:     0x55e0d098b8a8 - jujutsu::commands::dispatch::hf5768c8e6ca2007b
  23:     0x55e0d098cbd4 - jj::main::h9fc62cf2aaf605c0
  24:     0x55e0d098f603 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7ef9afa5a98051d7
  25:     0x55e0d098d039 - std::rt::lang_start::{{closure}}::h79f91634bb8322dc
  26:     0x55e0d0f2e971 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd05d8982c002a1a9
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/core/src/ops/function.rs:259:13
  27:     0x55e0d0f2e971 - std::panicking::try::do_call::ha2de91ec45a309aa
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/std/src/panicking.rs:492:40
  28:     0x55e0d0f2e971 - std::panicking::try::hf5d233d56c71d201
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/std/src/panicking.rs:456:19
  29:     0x55e0d0f2e971 - std::panic::catch_unwind::h10747b5e8afc13e6
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/std/src/panic.rs:137:14
  30:     0x55e0d0f2e971 - std::rt::lang_start_internal::{{closure}}::hcfc4e0221f952948
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/std/src/rt.rs:128:48
  31:     0x55e0d0f2e971 - std::panicking::try::do_call::h1bb4ffc2cf7b3c03
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/std/src/panicking.rs:492:40
  32:     0x55e0d0f2e971 - std::panicking::try::h73c86487a3602c03
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/std/src/panicking.rs:456:19
  33:     0x55e0d0f2e971 - std::panic::catch_unwind::h81db875d526be813
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/std/src/panic.rs:137:14
  34:     0x55e0d0f2e971 - std::rt::lang_start_internal::hc35357b91ce50efe
                               at /rustc/03a8cc7df1d65554a4d40825b0490c93ac0f0236/library/std/src/rt.rs:128:20
  35:     0x55e0d098cf62 - main
  36:     0x7f051dbbeb25 - __libc_start_main
  37:     0x55e0d098a69e - _start
  38:                0x0 - <unknown>
```

## Steps to Reproduce the Problem
Here's what I did:
1. copy an existing git clone: `cp -ar foo foo-test`
1. `cd foo-test`
1. `jj init --git-repo=.`
2. `cd ..`
3. `mv foo-test foo-jj-test`
4. `cd foo-jj-test`
5. `jj status #crash happens here`
6. `cd ..`
7. `mv foo-jj-test foo-test`
8. `cd foo-test`
9. `jj status #commands work again`

## Specifications

- Version: 0.2.0
- Platform: archlinux

**Comment by martinvonz** [comment]
Thanks for your report. The path is in `.jj/repo/store/git_target`, IIRC (on mobile now). We should make that a relative path at least when using `jj init --git-repo=.`. You can edit the file manually as a workaround for now.
